### ISSUE TITLE
numberplate-text=null in output file

### ISSUE THREAD

**Issue by adiljavaid** [oskopek/carcv#45] opened 2015-12-17 04:24 UTC
hi
following is the output file generated by carcv for only one image.
issue here is i didn't get the numberplate-text.
[
#test_030.jpg
#Wed Dec 16 14:48:55 PKT 2015
address-long=0.0
address-postalCode=93221
numberplate-text=null
address-street=Hru\u00C5\u00A1kov\u00C3\u00A1
address-city=Bratislava
speed-value=1.2
address-refNo=1010
numberplate-origin=UN
address-streetNo=32
address-country=Slovakia
address-lat=0.0
timestamp=1450259334535
filepath0=D\:\\carcv_data\\in\\img\\test_030.jpg
speed-unit=KPH

]
 please help where i have to change in the code to get numberplate text?

**Comment by oskopek** [comment] 2015-12-17 15:03
This is a known issue ( #1 ) and actually not directly an issue of CarCV. The problem is in [JavaANPR](https://github.com/oskopek/javaanpr), the library we use for number plate detection.

It fails to recognize plates in several images I know of, thus returning `null`, which you see in `numberplate-text`. I'm afraid there's not much you can do about this, apart from:

a) giving CarCV/JavaANPR a different image (of the same car) and try to run it again
b) fixing JavaANPR to detect more plates
c) migrating CarCV to a different (read: better) detection library

**Comment by oskopek** [comment] 2015-12-17 15:14
Closing as a duplicate of #1

**Closed by oskopek** 2015-12-17 15:14 UTC
Labels: duplicate
